name: Components tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: yarn
      - run: yarn test:component:headless
      - name: Cypress run
        uses: cypress-io/github-action@v5
